name: iOS IPA Oluştur

on:
  push:
    branches: [ "main" ]

jobs:
  build_ios:
    name: iOS Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Bağımlılıkları İndir
        run: flutter pub get

      - name: Uygulamayı Derle
        run: |
          flutter build ios --release --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app .
          cd ..
          zip -r su_ic.ipa Payload

      - name: IPA'yı Yükle
        uses: actions/upload-artifact@v4
        with:
          name: su-ic-ios-app
          path: build/ios/iphoneos/su_ic.ipa
